### ISSUE TITLE
Elasticsearch Exception in thread

### ISSUE THREAD

**Issue by jonatanaxe** [faradey/madock#26]
Hi @faradey Have you ever faced this issue with Elasticsearch? It starts but crashes shortly after.

```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "jdk.internal.platform.CgroupInfo.getMountPoint()" because "anyController" is null
        at java.base/jdk.internal.platform.cgroupv2.CgroupV2Subsystem.getInstance(CgroupV2Subsystem.java:80)
        at java.base/jdk.internal.platform.CgroupSubsystemFactory.create(CgroupSubsystemFactory.java:114)
        at java.base/jdk.internal.platform.CgroupMetrics.getInstance(CgroupMetrics.java:177)
        at java.base/jdk.internal.platform.SystemMetrics.instance(SystemMetrics.java:29)
        at java.base/jdk.internal.platform.Metrics.systemMetrics(Metrics.java:58)
        at java.base/jdk.internal.platform.Container.metrics(Container.java:43)
        at jdk.management/com.sun.management.internal.OperatingSystemImpl.<init>(OperatingSystemImpl.java:182)
        at jdk.management/com.sun.management.internal.PlatformMBeanProviderImpl.getOperatingSystemMXBean(PlatformMBeanProviderImpl.java:280)
        at jdk.management/com.sun.management.internal.PlatformMBeanProviderImpl$3.nameToMBeanMap(PlatformMBeanProviderImpl.java:199)
        at java.management/sun.management.spi.PlatformMBeanProvider$PlatformComponent.getMBeans(PlatformMBeanProvider.java:195)
        at java.management/java.lang.management.ManagementFactory.getPlatformMXBean(ManagementFactory.java:689)
        at java.management/java.lang.management.ManagementFactory.getOperatingSystemMXBean(ManagementFactory.java:389)
        at org.elasticsearch.server.cli.DefaultSystemMemoryInfo.getOSBeanMemoryGetter(DefaultSystemMemoryInfo.java:30)
        at org.elasticsearch.server.cli.DefaultSystemMemoryInfo.<init>(DefaultSystemMemoryInfo.java:25)
        at org.elasticsearch.server.cli.JvmOptionsParser.jvmOptions(JvmOptionsParser.java:129)
        at org.elasticsearch.server.cli.JvmOptionsParser.determineJvmOptions(JvmOptionsParser.java:90)
        at org.elasticsearch.server.cli.ServerProcess.createProcess(ServerProcess.java:211)
        at org.elasticsearch.server.cli.ServerProcess.start(ServerProcess.java:106)
        at org.elasticsearch.server.cli.ServerProcess.start(ServerProcess.java:89)
        at org.elasticsearch.server.cli.ServerCli.startServer(ServerCli.java:234)
        at org.elasticsearch.server.cli.ServerCli.execute(ServerCli.java:91)
        at org.elasticsearch.common.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:54)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:85)
        at org.elasticsearch.cli.Command.main(Command.java:50)
        at org.elasticsearch.launcher.CliToolLauncher.main(CliToolLauncher.java:64)
 *  Terminal will be reused by tasks, press any key to close it. 
```

**Comment by jonatanaxe** [comment]
@faradey  I changed the Elastic version from 8.4 to 8.11.4 and it works, but I found it strange that this issue started with the older version.
